#!/usr/bin/env node
/**
 * Transform dynamic plugin imports to static imports for Electron bundling.
 *
 * Dynamic imports like `import("@elizaos/plugin-sql")` cannot be bundled by
 * tsdown/rolldown because they're not statically analyzable. This script
 * transforms eliza.ts to use static imports that the bundler can inline.
 *
 * Usage: bun run scripts/transform-plugins-for-electron.ts
 *
 * This script is intended to be run during the Electron release build,
 * NOT during normal development or testing.
 */

import fs from "node:fs";
import path from "node:path";

const ELIZA_PATH = path.join(
  import.meta.dirname,
  "..",
  "src",
  "runtime",
  "eliza.ts",
);

// List of all plugins that need static imports for bundling
const PLUGINS = [
  "@elizaos/plugin-sql",
  "@elizaos/plugin-local-embedding",
  "@elizaos/plugin-secrets-manager",
  "@elizaos/plugin-form",
  "@elizaos/plugin-knowledge",
  "@elizaos/plugin-rolodex",
  "@elizaos/plugin-trajectory-logger",
  "@elizaos/plugin-agent-orchestrator",
  "@elizaos/plugin-cron",
  "@elizaos/plugin-shell",
  "@elizaos/plugin-plugin-manager",
  "@elizaos/plugin-agent-skills",
  "@elizaos/plugin-pdf",
  "@elizaos/plugin-cua",
  "@elizaos/plugin-obsidian",
  "@elizaos/plugin-code",
  "@elizaos/plugin-repoprompt",
  "@elizaos/plugin-claude-code-workbench",
  "@elizaos/plugin-openai",
  "@elizaos/plugin-anthropic",
  "@elizaos/plugin-google-genai",
  "@elizaos/plugin-xai",
  "@elizaos/plugin-groq",
  "@elizaos/plugin-openrouter",
  "@elizaos/plugin-ollama",
  "@elizaos/plugin-deepseek",
  "@elizaos/plugin-mistral",
  "@elizaos/plugin-together",
  "@elizaos/plugin-pi-ai",
  "@elizaos/plugin-elizacloud",
];

function pluginToVarName(pkg: string): string {
  // @elizaos/plugin-sql -> pluginSql
  // @elizaos/plugin-local-embedding -> pluginLocalEmbedding
  return pkg
    .replace("@elizaos/plugin-", "plugin")
    .replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

function generateStaticImports(): string {
  const lines = [
    "// ---------------------------------------------------------------------------",
    "// AUTO-GENERATED: Static plugin imports for Electron bundling",
    "// This section is generated by scripts/transform-plugins-for-electron.ts",
    "// ---------------------------------------------------------------------------",
  ];

  for (const pkg of PLUGINS) {
    const varName = pluginToVarName(pkg);
    lines.push(`import * as ${varName} from "${pkg}";`);
  }

  lines.push("");
  lines.push("const BUNDLED_PLUGINS: Record<string, unknown> = {");
  for (const pkg of PLUGINS) {
    const varName = pluginToVarName(pkg);
    lines.push(`  "${pkg}": ${varName},`);
  }
  lines.push("};");
  lines.push("");

  return lines.join("\n");
}

function generateResolveFunction(): string {
  return `
/**
 * Resolve a plugin from the bundled static imports.
 * In the Electron build, all plugins are bundled statically.
 */
async function resolveStaticElizaPlugin(
  pluginName: string,
): Promise<unknown | null> {
  return BUNDLED_PLUGINS[pluginName] ?? null;
}
`.trim();
}

function transformElizaFile(): void {
  console.log("Reading eliza.ts...");
  let content = fs.readFileSync(ELIZA_PATH, "utf-8");

  // Find the location to insert static imports (after the last import from @elizaos/core)
  const coreImportMatch = content.match(/from "@elizaos\/core";/);
  if (!coreImportMatch) {
    throw new Error("Could not find @elizaos/core import in eliza.ts");
  }

  const insertPos =
    content.indexOf(coreImportMatch[0]) + coreImportMatch[0].length;

  // Generate static imports
  const staticImports = generateStaticImports();

  // Insert static imports after the @elizaos/core import
  content =
    content.slice(0, insertPos) +
    "\n\n" +
    staticImports +
    content.slice(insertPos);

  // Find and replace the resolveStaticElizaPlugin function
  const funcStartPattern = new RegExp(
    "async function resolveStaticElizaPlugin\\(\\s*" +
      "pluginName: string,?\\s*\\):\\s*" +
      "Promise<unknown \\| null>\\s*\\{",
  );
  const funcStartMatch = content.match(funcStartPattern);

  if (!funcStartMatch) {
    throw new Error("Could not find resolveStaticElizaPlugin function");
  }

  const funcStart = content.indexOf(funcStartMatch[0]);

  // Find the matching closing brace by counting braces
  let braceCount = 0;
  let funcEnd = funcStart;
  let foundOpenBrace = false;

  for (let i = funcStart; i < content.length; i++) {
    if (content[i] === "{") {
      braceCount++;
      foundOpenBrace = true;
    } else if (content[i] === "}") {
      braceCount--;
      if (foundOpenBrace && braceCount === 0) {
        funcEnd = i + 1;
        break;
      }
    }
  }

  // Replace the function
  const newFunc = generateResolveFunction();
  content = content.slice(0, funcStart) + newFunc + content.slice(funcEnd);

  // Write the transformed file
  console.log("Writing transformed eliza.ts...");
  fs.writeFileSync(ELIZA_PATH, content);
  console.log("Done! eliza.ts has been transformed for Electron bundling.");
}

// Run the transformation
transformElizaFile();
